import:
  - display/desktop/xsetroot
  - display/color/zenburn
  - display/client
  - display/tags
  - display/status/arrange
#  - display/status/notice
#  - display/status/weather
#  - display/status/pomodoro
#  - display/status/music/mpd
#  - display/status/network
#  - display/status/disk
  - display/status/load
#  - display/status/memory
#  - display/status/power
  - display/status/volume
  - display/status/time
  - control/keyboard/qwerty
  - control/keyboard/qwerty/arrange_by_number
  - control/keyboard/qwerty/client
  - control/keyboard/qwerty/detach
  - control/keyboard/qwerty/focus
  - control/keyboard/qwerty/focus_by_letter
  - control/keyboard/qwerty/focus_by_number
  - control/keyboard/qwerty/group
  - control/keyboard/qwerty/launch
  - control/keyboard/qwerty/layout
  - control/keyboard/qwerty/layout_by_number
  - control/keyboard/qwerty/menu
  - control/keyboard/qwerty/move
  - control/keyboard/qwerty/move_by_number
  - control/keyboard/qwerty/resize
  - control/keyboard/qwerty/swap
  - control/keyboard/qwerty/swap_by_number
  - control/keyboard/qwerty/zoom
  - control/mouse
  - control/workdir

prefer:
  terminal: urxvtc
  browser:  firefox
  editor:   gvim
  filer:    vim

display:
  bar: bottom
  font: "xft:Inconsolata:size=11:antialias=1:hinting=1:hintstyle=hintfull"
  border: 2
  column:
    mode: stack
    rule: |
      /art/ -> 17+83+41
      /com/ -> 82+18
      /.*/ -> 50+50
  client:
    rule: |
      /^pcmanfm:/ group=0
      /^firefox/ tags=net
      /^thunderbird/ tags=com

      /^zim:/ tags=note

      /^gimp:/ tags=art


      /^vncviewer:/ floating=on
      /^alsaplayer:/ floating=on
      /:MPlayer:/ floating=on
      /^xmessage:/ floating=on tags=/./
      /^xmag:/ floating=on
      /^arandr:/ floating=on
      /^pinentry/ floating=on
      /^tkmidity/ floating=on
      /^<nil>:<nil>:Event Tester$/ floating=on # xev
  status:
    arrange:
      '@choices':
        right_stack: |
          tile_right
          managed_areas.last.layout = :stack
    time:
      '@format': '%a %b %d, %R'
      refresh: 30
      mouse_action:
        right_click: lock_screen
    volume:
      '@mixer': Master
    disk:
      '@path': $HOME
    network:
      instances:
        - '@interface': wlan0
        - '@interface': eth0
          refresh: 60

control:
  keyboard:
    mod:     Mod4
    view:    Mod4-Shift-v
    move:    Mod4-Shift
    swap:    Mod4-r
    group:   Mod4-g
    layout:  Mod4-w
    arrange: Mod4-Shift-w
    resize:  Mod4-Control

    prev:    comma
    next:    period
  action:
    lock_screen: launch 'xtrlock'
    show_battery_info: dialog `acpitool -b -i`

